### ISSUE TITLE
Não está mais funcionando.

### ISSUE THREAD

**Issue by lukefeix** [cleitonleonel/TraderTimerZone#1]
Tentei  puxar os dados , retornam none.

**Comment by cleitonleonel** [comment]
> Tentei puxar os dados , retornam none.

![image](https://github.com/cleitonleonel/TraderTimerZone/assets/11451914/3d1c7560-9ba9-4c70-bdbe-a4f6fcbfedff)

**Comment by lukefeix** [comment]
Que estranho, aqui o request retorna como None a conexão da página. tentei também mudar algumas coisas mas sem sucesso, não consegue fazer a conexão.
![Captura de tela 2023-10-05 092045](https://github.com/cleitonleonel/TraderTimerZone/assets/67929862/0dd2f084-73ad-4e9d-b073-29bc1c8fb022)

**Comment by cleitonleonel** [comment]
> Que estranho, aqui o request retorna como None a conexão da página. tentei também mudar algumas coisas mas sem sucesso, não consegue fazer a conexão. ![Captura de tela 2023-10-05 092045](https://private-user-images.githubusercontent.com/67929862/272900422-0dd2f084-73ad-4e9d-b073-29bc1c8fb022.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxODE5MTcsIm5iZiI6MTcyMDE4MTYxNywicGF0aCI6Ii82NzkyOTg2Mi8yNzI5MDA0MjItMGRkMmYwODQtNzNhZC00ZTlkLWIwNzMtMjliYzFjOGZiMDIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA1VDEyMTMzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyNDlhNDU4MDIxZWUxNzVjODc0ZjE1MDNmYzMzNzQwZGQ2M2IxYjZiMmVlYTZkMzAwNzAwOTYyNzE4ODE3YjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.khODcO0_uHQEm7hKtOVd7E9VBoxdQXGkn0x2WR-4Wuw)

Talvez seja um pouco trade, mas fiz uma correção nesse código...

https://github.com/cleitonleonel/TraderTimerZone/commit/d98d67e27c82f1b438f883ff11c61cbbf8827558
